Improved rewrite and routing possibilites
New settings for vhosts.*.rewrite:
precondition: Value is either 404 or 403 - The rule is only executed if
the server would otherwise send 404 or 403
headers: Unlimited amount of name-value-pairs of headers that will be
sent to the client
destination: Absolute URI that the client will be redirected to (for
example "destination: http://google.com/")
exception: Value can be any valid HTTP answer code - Causes an
invalidHTTPRequestException
exceptionMessage: Sets a message for the exception - Defaults to "The
server was unable to process your request"

See vhost.example.yml for further examples